// storage.js

export const tabooDataTest = [
    { guessWord: 'Apple', tabooWords: ['Fruit', 'Red', 'Tree','ADAM','EVE'] },
    { guessWord: 'Orange', tabooWords: ['Fruit', 'Red', 'Tree','ADAM','EVE'] },
    { guessWord: 'peas', tabooWords: ['Fruit', 'Green', 'Pod', 'ADAM','EVE']},
    { guessWord: 'goat', tabooWords: ['Fruit', 'Red', 'Tree', 'ADAM','EVE'] },
  ];

  export const tabooData = [
    { guessWord: 'Bottle', tabooWords: ['Milk', 'Nipple', 'Formula', 'Feed', 'Baby'] },
    { guessWord: 'Diaper Bag', tabooWords: ['Diaper', 'Wipes', 'Change', 'Supplies', 'Travel'] },
    { guessWord: 'Pacifier', tabooWords: ['Soothe', 'Comfort', 'Suck', 'Baby', 'Binky'] },
    { guessWord: 'Onesie', tabooWords: ['Clothing', 'Snap', 'Cute', 'Baby', 'Apparel'] },
    { guessWord: 'Baby Shower', tabooWords: ['Celebration', 'Gifts', 'Friends', 'Party', 'Congratulations'] },
    { guessWord: 'Stroller', tabooWords: ['Walk', 'Baby', 'Mobile', 'Push', 'Transport'] },
    { guessWord: 'Crib', tabooWords: ['Sleep', 'Baby', 'Nursery', 'Bed', 'Furniture'] },
    { guessWord: 'Baby Blanket', tabooWords: ['Warm', 'Snuggle', 'Soft', 'Baby', 'Bedding'] },
    { guessWord: 'Pregnant', tabooWords: ['Expecting', 'Knocked up', 'Belly', 'Baby', 'Mom'] },
    { guessWord: 'Baby Monitor', tabooWords: ['Watch', 'Hear', 'Sounds', 'Baby', 'Video'] },

    { guessWord: 'Baby Powder', tabooWords: ['Soft', 'Fragrance', 'Diaper', 'White', 'Fresh'] },
    { guessWord: 'Rattle', tabooWords: ['Shake', 'Sound', 'Toy', 'Baby', 'Play'] },
    { guessWord: 'Bib', tabooWords: ['Eat', 'Food', 'Cloth', 'Baby', 'Drool'] },
    { guessWord: 'Nursery Rhyme', tabooWords: ['Song', 'Children', 'Story', 'Music', 'Rhyme'] },
    { guessWord: 'Nap Time', tabooWords: ['Sleep', 'Rest', 'Quiet', 'Baby', 'Recharge'] },
    { guessWord: 'Cradle', tabooWords: ['Rock', 'Sleep', 'Baby', 'Bed', 'Comfort'] },
    { guessWord: 'Baby Cup', tabooWords: ['Drink', 'Sip', 'Training', 'Baby', 'Bottle'] },
    { guessWord: 'Playpen', tabooWords: ['Safe', 'Play', 'Contain', 'Baby', 'Balls'] },
    { guessWord: 'Changing Table', tabooWords: ['Diaper Change', 'Baby', 'Nursery', 'Convenience', 'Table'] },
    { guessWord: 'Teether', tabooWords: ['Chew', 'Soothe', 'Gums', 'Baby', 'Relief'] },

    { guessWord: 'Nail Clippers', tabooWords: ['Trim', 'Nails', 'Baby', 'Grooming', 'Care'] },
    { guessWord: 'Baby Formula', tabooWords: ['Feed', 'Milk', 'Baby', 'Nutrition', 'Bottle'] },
    { guessWord: 'Changing Pad', tabooWords: ['Diaper Change', 'Baby', 'Nursery', 'Convenience', 'Pad'] },
    { guessWord: 'Diaper Rash Cream', tabooWords: ['Soothe', 'Protect', 'Baby', 'Skin', 'Itch'] },
    { guessWord: 'Bath Thermometer', tabooWords: ['Water', 'Bath', 'Baby', 'Temperature', 'Hot'] },
    { guessWord: 'Wet Wipes', tabooWords: ['Clean', 'Diaper Change', 'Baby', 'Hygiene', 'Disposable'] },
    { guessWord: 'Pediatrician', tabooWords: ['Baby', 'Doctor', 'Born', 'Infant', 'Shots'] },
    { guessWord: 'Labor', tabooWords: ['Contractions', 'Hospital', 'Baby', 'Delivery', 'Born'] },
    { guessWord: 'Epidural', tabooWords: ['Needle', 'Numb', 'Pain', 'Feel', 'Birth'] },
    { guessWord: 'Breast Feeding', tabooWords: ['Boobs', 'Milk', 'Feed', 'Nipple', 'Breasts'] },

    { guessWord: 'Umbilical Cord', tabooWords: ['Belly button', 'Food', 'Nourishment', 'Placenta', 'Connects'] },
    { guessWord: 'Stretch Marks', tabooWords: ['Rip', 'Tear', 'Skin', 'Hips', 'Belly'] },
    { guessWord: 'Contractions', tabooWords: ['Braxton Hicks', 'Delivery', 'Tighten', 'Baby', 'Pain'] },
    { guessWord: 'Diaper', tabooWords: ['Dirty', 'Smelly', 'Poop', 'Bottom', 'Butt'] },
    { guessWord: 'Ultrasound', tabooWords: ['Picture', '3d', 'Gender', 'Machine', 'Belly'] },
    { guessWord: 'Morning Sickness', tabooWords: ['Nausea', 'Bed', 'Throw up', 'Green', 'Feel'] },
    { guessWord: 'Bed Rest', tabooWords: ['Doctor', 'Risk', 'Complications', 'Baby', 'Sleep'] },
    { guessWord: 'Birth Canal', tabooWords: ['Birth', 'Deliver', 'Baby', 'Tunnel', 'Emerges'] },
    { guessWord: 'Circumcision', tabooWords: ['Boy', 'Penis', 'Cut', 'Doctor', 'Snip'] },
    { guessWord: 'Baby', tabooWords: ['Fetus', 'Infant', 'Newborn', 'Belly', 'Diapers'] },

    { guessWord: 'Due Date', tabooWords: ['Birthday', 'Baby', 'Born', 'Delivery', 'Hospital'] },
    { guessWord: 'Lullaby', tabooWords: ['Sing', 'Baby', 'Soothe', 'Rock', 'Song'] },
    { guessWord: 'Midwife', tabooWords: ['Nurse', 'Delivery', 'Labor', 'Pregnant', 'Assist'] },
    { guessWord: 'Uterus', tabooWords: ['Womb', 'Eggs', 'Sex', 'Baby', 'Ovaries'] },
    { guessWord: 'Pediatrician', tabooWords: ['Baby', 'Doctor', 'Born', 'Infant', 'Shots'] },
    { guessWord: 'Lamaze', tabooWords: ['Classes', 'Breathing', 'Exercise', 'Couple', 'Baby'] },
    { guessWord: 'Nipple', tabooWords: ['Breast', 'Milk', 'Bite', 'Feed', 'Suck'] },
    { guessWord: 'Home Birth', tabooWords: ['Place', 'Born', 'Hospital', 'Deliver', 'Doctor'] },
    { guessWord: 'Car Seat', tabooWords: ['Drive', 'Sleeps', 'Chair', 'Leave', 'Belt'] },
    { guessWord: 'Bath', tabooWords: ['Water', 'Tub', 'Shower', 'Soap', 'Bubbles'] },

    { guessWord: 'Trimester', tabooWords: ['Three', 'Months', 'Weeks', 'First', 'Pregnancy'] },
    { guessWord: 'Swing', tabooWords: ['Sway', 'Rock', 'Sit', 'Music', 'Move'] },
    { guessWord: 'Burp', tabooWords: ['Feed', 'Gas', 'Back', 'Pat', 'Spit Up'] },
    { guessWord: 'Giggle', tabooWords: ['Laugh', 'Smile', 'Happy', 'Sound', 'Cackle'] },
    { guessWord: 'Towel', tabooWords: ['Bath', 'Dry', 'Shower', 'Soft', 'Hooded'] },
    { guessWord: 'Sleep', tabooWords: ['Rest', 'Bed', 'Eyes', 'Deprived', 'Night'] },
    { guessWord: 'Swaddle', tabooWords: ['Wrap', 'Fabric', 'Arms', 'Snuggle', 'Blanket'] },
    { guessWord: 'Hospital', tabooWords: ['Doctor', 'Birth', 'Labor', 'Delivery', 'Stay'] },
    { guessWord: 'Father', tabooWords: ['Mother', 'Parent', 'Dad', 'Man', 'Baby'] },
    { guessWord: 'Mother', tabooWords: ['Mom', 'Woman', 'Parent', 'Baby', 'Maternal'] },

    { guessWord: 'Crawl', tabooWords: ['Walk', 'Move', 'Fours', 'Motion', 'Knees'] },
    { guessWord: 'Crying', tabooWords: ['Sad', 'Tears', 'Scream', 'Noise', 'Pain'] },
    { guessWord: 'Booties', tabooWords: ['Slippers', 'Shoes', 'Feet', 'Knitted', 'Sock'] },
    { guessWord: 'Boy', tabooWords: ['Male', 'Man', 'Lad', 'Son', 'Junior'] },
    { guessWord: 'Girl', tabooWords: ['Female', 'Lady', 'Daughter', 'Miss', 'Woman'] },
    { guessWord: 'Party', tabooWords: ['Invite', 'Family', 'Friends', 'Dance', 'Music'] },
    { guessWord: 'Twins', tabooWords: ['Two', 'Multiples', 'Identical', 'Fraternal', 'Lookalike'] },
    { guessWord: 'Belly', tabooWords: ['Round', 'Big', 'Heavy', 'Grow', 'Stomach'] },
    { guessWord: 'Home', tabooWords: ['House', 'Family', 'Nursery', 'Live', 'Land'] },
    { guessWord: 'Triplets', tabooWords: ['Three', 'Multiples', 'Plural', 'Twins', 'Trio'] },

    { guessWord: 'Snuggle', tabooWords: ['Hug', 'Embrace', 'Love', 'Cosy', 'Cuddle'] },
    { guessWord: 'Sling', tabooWords: ['Carry', 'Support', 'Hold', 'Strap', 'Suspend'] },
    { guessWord: 'Baby Food', tabooWords: ['Eat', 'Puree', 'Baby', 'Spoon', 'Jar'] },
    { guessWord: 'Stork', tabooWords: ['Bird', 'Myth', 'Delivery', 'Door', 'Feathers'] },
    { guessWord: 'Push', tabooWords: ['Labor', 'Delivery', 'Birth', 'Force', 'Contractions'] },
    { guessWord: 'Socks', tabooWords: ['Shoes', 'Underwear', 'Feet', 'Warm', 'Pairs'] },
    { guessWord: 'Newborn', tabooWords: ['Infant', 'Baby', 'Birth', 'Young', 'Cradle'] },
    { guessWord: 'Blue', tabooWords: ['Color', 'Sky', 'Ocean', 'Azure', 'Boy'] },
    { guessWord: 'Pink', tabooWords: ['Color', 'Rose', 'Girl', 'Bubblegum', 'Fuchsia'] },
    { guessWord: 'Nursery', tabooWords: ['Room', 'Baby', 'Crib', 'Decor', 'Bed'] },

    { guessWord: 'Pampers', tabooWords: ['Diapers', 'Brand', 'Baby', 'Change', 'Poop'] },
    { guessWord: 'Johnson & Johnson', tabooWords: ['Brand', 'Baby', 'Products', 'Powder', 'Lotion'] },
    { guessWord: 'Bassinet', tabooWords: ['Cradle', 'Sleep', 'Baby', 'Bed', 'Nursery'] },
    { guessWord: 'Breast Milk', tabooWords: ['Boobs', 'Feeding', 'Mother', 'Baby', 'Lactation'] },
    { guessWord: 'Mobile', tabooWords: ['Hanging', 'Toy', 'Crib', 'Rotate', 'Crib'] },
    { guessWord: 'Hiccup', tabooWords: ['Spasm', 'Water', 'Breath', 'Sound', 'Involuntary'] },
    { guessWord: 'Massage', tabooWords: ['Relax', 'Therapy', 'Hands', 'Spa', 'Parlor'] },
    { guessWord: 'Coffee', tabooWords: ['Awake', 'Caffeine', 'Morning', 'Drink', 'Roast'] },
    { guessWord: 'Mittens', tabooWords: ['Gloves', 'Hands', 'Warm', 'Winter', 'Fingers'] },
    { guessWord: 'Nurse', tabooWords: ['Doctor', 'Breastfeed', 'Suckle', 'Caregiver', 'Hospital'] },

  ]






