name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.9.0'

    - name: Install dependencies
      run: npm install

    - name: Verify React installation
      run: npm ls react react-dom

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Set git user
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        npm install gh-pages --save-dev
        npm run deploy
